### ISSUE TITLE
Add to plugins.octoprint.org

### ISSUE THREAD

**Issue by guysoft** [cprasmu/OctoPrint-OrviboS20#5]
Hey,
now that the plugin is working, you can add it to the repository here:
https://plugins.octoprint.org/help/registering/

**Comment by cprasmu** [comment]
Yes totally agree, I want to check that everything works as expected as there is a couple of bit commented out that need looking at and then I will get it added. Will try and take a look this weekend

**Comment by cprasmu** [comment]
The pull request is in !

**Comment by cprasmu** [comment]
It’s live !
